sudo: required

services:
  - docker

before_install:
  - docker build -t denyslins/udemy-react-multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true denyslins/udemy-react-multi-client-test npm test -- --coverage

after_success:
  - docker build -t denyslins/udemy-react-multi-client ./client
  - docker build -t denyslins/udemy-react-multi-nginx ./nginx
  - docker build -t denyslins/udemy-react-multi-server ./server
  - docker build -t denyslins/udemy-react-multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push denyslins/udemy-react-multi-client
  - docker push denyslins/udemy-react-multi-nginx
  - docker push denyslins/udemy-react-multi-server
  - docker push denyslins/udemy-react-multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemy-multi-docker"
  env: "UdemyMultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-364239297740"
  bucket_path: "udemy-multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
