sudo: required

services:
  - docker

before_install:
  - docker build -t denyslins/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true denyslins/react-test npm test -- --coverage

after_success:
  - docker build -f denyslins/udemy-react-multi-client ./client
  - docker build -f denyslins/udemy-react-multi-nginx ./nginx
  - docker build -f denyslins/udemy-react-multi-server ./server
  - docker build -f denyslins/udemy-react-multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push denyslins/udemy-react-multi-client
  - docker push denyslins/udemy-react-multi-nginx
  - docker push denyslins/udemy-react-multi-server
  - docker push denyslins/udemy-react-multi-worker
